services:
  config-server:
    image: "rekindle/rekindle-book-shop-config-server"
    container_name: configserver-container
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - EUREKA_HOST=eurekaserver-container
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      rekindle-network:
        aliases:
          - "configserver-container"

  eureka-server:
    image: "rekindle/rekindle-book-shop-eureka-server"
    container_name: eurekaserver-container
    ports:
      - "9001:9001"
    healthcheck:
      test: "curl --fail --silent localhost:9001/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      - CONFIG_HOST=configserver-container
      - EUREKA_HOST=eurekaserver-container
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      rekindle-network:
        aliases:
          - "eurekaserver-container"

  auth-server:
    image: "rekindle/rekindle-book-shop-auth-server"
    container_name: authserver-container
    ports:
      - "9010:9010"
    healthcheck:
      test: "curl --fail --silent localhost:9010/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      - CONFIG_HOST=configserver-container
      - EUREKA_HOST=eurekaserver-container
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      rekindle-network:
        aliases:
          - "authserver-container"

  book-service:
    image: "rekindle/rekindle-book-shop-book-service"
    container_name: bookservice-container
    ports:
      - "9020:9020"
    healthcheck:
      test: "curl --fail --silent localhost:9020/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      - CONFIG_HOST=configserver-container
      - EUREKA_HOST=eurekaserver-container
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      rekindle-network:
        aliases:
          - "bookservice-container"

networks:
  rekindle-network:
    name: rekindle-network
    driver: "bridge"