x-infra: &infra
  zookeeper-service:
    condition: service_healthy
  kafka-broker-1:
    condition: service_healthy
  kafka-broker-2:
    condition: service_healthy
  kafka-broker-3:
    condition: service_healthy
  schema-registry:
    condition: service_healthy
  postgres:
    condition: service_healthy
  database-seed:
    condition: service_completed_successfully
  init-kafka-topics:
    condition: service_completed_successfully

services:
  eureka-server:
    image: rekindle/eureka-server
    build:
      context: ../../
      dockerfile: infrastructure/eureka-server/Dockerfile
    ports:
      - "8761:8761"
    env_file:
      - ./.env
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    profiles:
      - all
      - app
      - eureka
    depends_on:
      <<: [ *infra ]

  config-server:
    image: rekindle/config-server
    build:
      context: ../../
      dockerfile: infrastructure/config-server/Dockerfile
    profiles:
      - all
      - app
      - config
    ports:
      - "8021:8021"
    env_file:
      - ./.env
    environment:
      - CONFIG_HOST=config-server
      - EUREKA_HOST=eureka-server
      - AUTH_HOST=authorization-server
    healthcheck:
      test: "curl --fail --silent localhost:8021/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      <<: [ *infra ]
      eureka-server:
        condition: service_healthy

  authorization-server:
    image: rekindle/authorization-server
    build:
      context: ../../
      dockerfile: infrastructure/authorization-server/Dockerfile
    profiles:
      - all
      - app
      - auth
    ports:
      - "8023:8023"
    healthcheck:
      test: "curl --fail --silent localhost:8023/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=eureka
      - CONFIG_HOST=config-server
      - EUREKA_HOST=eureka-server
      - AUTH_HOST=authorization-server
    depends_on:
      <<: [ *infra ]
      config-server:
        condition: service_healthy

  bookstore-microservice:
    image: rekindle/bookstore-service
    build:
      context: ../../
      dockerfile: bookstore-service/bookstore-microservice/Dockerfile
    profiles:
      - all
      - app
      - book
    ports:
      - "8183:8183"
    healthcheck:
      test: "curl --fail --silent localhost:8183/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=postgre,kafka-docker,eureka
    depends_on:
      <<: [ *infra ]
      config-server:
        condition: service_healthy

  order-microservice:
    image: rekindle/order-service
    build:
      context: ../../
      dockerfile: order-service/order-microservice/Dockerfile
    profiles:
      - all
      - app
      - order
    ports:
      - "8181:8181"
    env_file:
      - ./.env
    healthcheck:
      test: "curl --fail --silent localhost:8181/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      - SPRING_PROFILES_ACTIVE=postgre,kafka-docker,eureka
    depends_on:
      <<: [ *infra ]
      config-server:
        condition: service_healthy

  payment-microservice:
    image: rekindle/payment-service
    build:
      context: ../../
      dockerfile: payment-service/payment-microservice/Dockerfile
    profiles:
      - all
      - app
      - payment
    ports:
      - "8182:8182"
    env_file:
      - ./.env
    healthcheck:
      test: "curl --fail --silent localhost:8182/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      - SPRING_PROFILES_ACTIVE=postgre,kafka-docker,eureka
    depends_on:
      <<: [ *infra ]
      config-server:
        condition: service_healthy

  customer-microservice:
    image: rekindle/customer-service
    build:
      context: ../../
      dockerfile: customer-service/customer-microservice/Dockerfile
    profiles:
      - all
      - app
      - customer
    env_file:
      - ./.env
    ports:
      - "8184:8184"
    healthcheck:
      test: "curl --fail --silent localhost:8184/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      - SPRING_PROFILES_ACTIVE=postgre,eureka
    depends_on:
      <<: [ *infra ]
      config-server:
        condition: service_healthy

  gateway-server:
    image: rekindle/gateway-service
    build:
      context: ../../
      dockerfile: infrastructure/gateway-server/Dockerfile
    healthcheck:
      test: "curl --fail --silent localhost:8024/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    profiles:
      - all
      - app
      - gateway
    env_file:
      - ./.env
    ports:
      - "8024:8024"
    environment:
      - SPRING_PROFILES_ACTIVE=eureka
    depends_on:
      <<: [ *infra ]
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy