networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/24
services:
  zookeeper-service:
    image: confluentinc/cp-zookeeper:${ZOOKEEPER_VERSION}
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok"
    healthcheck:
      test: [ "CMD-SHELL","echo ruok | nc 127.0.0.1 2181 | grep imok || exit -1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - "./volumes/zookeeper/data:/var/lib/zookeeper/data 777"
      - "./volumes/zookeeper/transactions:/var/lib/zookeeper/log 777"
    env_file:
      - ./.env
    profiles:
      - infra
      - zookeeper

  kafka-broker-1:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: kafka-broker-1
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,LISTENER_LOCAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    env_file:
      - ./.env
    healthcheck:
      test: kafka-topics --bootstrap-server kafka-broker-1:9092 --list
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      zookeeper-service:
        condition: service_healthy
    volumes:
      - "./volumes/kafka/broker-1:/var/lib/kafka/data 777"
    profiles:
      - infra
      - broker_1

  kafka-broker-2:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9092,LISTENER_LOCAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    env_file:
      - ./.env
    healthcheck:
      test: kafka-topics --bootstrap-server kafka-broker-2:9092 --list
      interval: 10s
      timeout: 5s
      retries: 10
    profiles:
      - infra
      - broker_2
    depends_on:
      zookeeper-service:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
    volumes:
      - "./volumes/kafka/broker-2:/var/lib/kafka/data 777"

  kafka-broker-3:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: kafka-broker-3
    ports:
      - "39092:39092"
    profiles:
      - infra
      - broker_3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:9092,LISTENER_LOCAL://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    env_file:
      - ./.env
    healthcheck:
      test: kafka-topics --bootstrap-server kafka-broker-3:9092 --list
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      zookeeper-service:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
    volumes:
      - "./volumes/kafka/broker-3:/var/lib/kafka/data 777"

  schema-registry:
    image: confluentinc/cp-schema-registry:${KAFKA_VERSION}
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "8081:8081"
    profiles:
      - infra
      - registry
    healthcheck:
      test: curl --output /dev/null --silent --head --fail http://schema-registry:8081/subjects
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper-service:2181'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker-2:9092,LISTENER_LOCAL://localhost:29092
      SCHEMA_REGISTRY_DEBUG: 'true'

  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
    profiles:
      - infra
      - manager
    depends_on:
      schema-registry:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3
    ports:
      - "5432:5432"
    profiles:
      - infra
      - db
    volumes:
      - "./volumes/postgre:/var/lib/postgresql/data 777"