services:
  database-seed:
    image: rekindle/db-migrate
    build:
      context: ../../
      dockerfile: infrastructure/database-migrations/Dockerfile
    env_file:
      - ./.env
    environment:
      POSTGRE_URL: postgres
    profiles:
      - infra
      - seed
    depends_on:
      postgres:
        condition: service_healthy