networks:
  rekindle-bookstore-network:
    driver: bridge
services:
  zookeeper:
    user: "${UID}:${GID}"
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok"
    healthcheck:
      test: [ "CMD-SHELL","echo ruok | nc localhost 2181 | grep imok || exit -1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - "./volumes/zookeeper/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper/transactions:/var/lib/zookeeper/log"
    networks:
      rekindle-bookstore-network:
        aliases:
          - "zookeeper"
  kafka-broker-1:
    user: "${UID}:${GID}"
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-1
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,LISTENER_LOCAL://165.232.113.133:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    healthcheck:
      test: kafka-topics --bootstrap-server kafka-broker-1:9092 --list
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      zookeeper:
        condition: service_healthy
    volumes:
      - "./volumes/kafka/broker-1:/var/lib/kafka/data"
    networks:
      rekindle-bookstore-network:
        aliases:
          - "kafka-broker-1"
  kafka-broker-2:
    user: "${UID}:${GID}"
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-2
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9092,LISTENER_LOCAL://165.232.113.133:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    healthcheck:
      test: kafka-topics --bootstrap-server kafka-broker-2:9092 --list
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
    volumes:
      - "./volumes/kafka/broker-2:/var/lib/kafka/data"
    networks:
      rekindle-bookstore-network:
        aliases:
          - "kafka-broker-2"
  kafka-broker-3:
    user: "${UID}:${GID}"
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-3
    ports:
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:9092,LISTENER_LOCAL://165.232.113.133:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    healthcheck:
      test: kafka-topics --bootstrap-server kafka-broker-3:9092 --list
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
    volumes:
      - "./volumes/kafka/broker-3:/var/lib/kafka/data"
    networks:
      rekindle-bookstore-network:
        aliases:
          - "kafka-broker-3"
  schema-registry:
    user: "${UID}:${GID}"
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: curl --output /dev/null --silent --head --fail http://schema-registry:8081/subjects
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker-2:9092,LISTENER_LOCAL://165.232.113.133:29092
      SCHEMA_REGISTRY_DEBUG: 'true'
    networks:
      rekindle-bookstore-network:
        aliases:
          - "schema-registry"
  kafka-manager:
    user: "${UID}:${GID}"
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
    depends_on:
      schema-registry:
        condition: service_healthy
    networks:
      rekindle-bookstore-network:
        aliases:
          - "kafka-manager"