server:
  port: 8023
spring:
  application:
    name: "authorization-server"
  profiles:
    active: "local"
  config:
    import: "optional:configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8021}/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true