server:
  port: 8184
spring:
  application:
    name: "customer-microservice"
  config:
    import: "configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8021}/"
logging:
  level:
    com.rekindle.book.store: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true