spring:
  application:
    name: "eureka-server"
  profiles:
    active: "local"
  config:
    import: "optional:configserver:http://${CONFIG_HOST:localhost}:9000/"
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWIthEureka: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:9001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true