server:
  port: 8761
spring:
  application:
    name: "eureka-server"
eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    fetchRegistry: false
    registerWIthEureka: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true